### ISSUE TITLE
Added NewLine to output when using this vs Trace

### ISSUE THREAD

**Issue by HakanL** [serilog/serilog-sinks-debug#3]
I used to use the Trace sink with this output template:
`{Timestamp:HH:mm:ss.fff} {Logger} [{Level:u3}] {Message}{NewLine}{Exception}`

and my output would be clean-ish (info and warnings would have prefixes, that's why I switched to Debug):

> 16:46:38.226  [VRB] Received local payload "IO.DigitalInputChanged", destination null
> 16:46:38.230  [VRB] Received local payload "IO.DigitalInputChanged", destination null

But when I switch to the Debug sink I'm now getting an empty newline after each log message. I only want it when there's an exception:

>16:49:42.167  [VRB] Received local payload "IO.DigitalInputChanged", destination null
>
>16:49:42.172  [VRB] Received local payload "IO.DigitalInputChanged", destination null

Is it missing a Trim() perhaps? If I don't have the {NewLine} in the template then I get the start of the exception logging on the main log line, I want it on its own line, like the Trace sink does.

**Comment by HakanL** [comment]
I just compared the Trace and Debug source, and yes, there is a Trim() in the Trace sink, but not in the Debug sink.

**Comment by HakanL** [comment]
Added PR, please consider merging.

**Comment by HakanL** [comment]
I tested this in UWP using version 1.0.1 and it works great now!

**Comment by ches151** [comment]
Thank you for addressing the issue. When will the updated version become available via NuGet?

**Comment by nblumhardt** [comment]
@ches151 thanks for the nudge! Looks like the publishing failed, will dig into it now.

**Comment by nblumhardt** [comment]
Done!
