### ISSUE TITLE
Question. Why `Serilog.Sinks.Debug` causes downloading of `System.Diagnostics.Debug` NuGet package when my project targets .NET Framework 4.7.1?

### ISSUE THREAD

**Issue by ches151** [serilog/serilog-sinks-debug#6]
Why `Serilog.Sinks.Debug` causes downloading of `System.Diagnostics.Debug` NuGet package when my project targets .NET Framework 4.7.1?
Isn't `System.Diagnostics.Debug` a part of .NET Framework 4.7.1?

**Comment by Numpsy** [comment]
I don't *think* it should need to reference the ```System.Diagnostics.Debug``` package for any of the target frameworks it builds with other than netstandard1.0 (though maybe netstandard1.0 isn't much needed going forwards?) - it should be built in for both full .NET framework and netstandard2.0

**Comment by Numpsy** [comment]
this should be fixed in the current preview builds

**Comment by nblumhardt** [comment]
Coming shortly in #13
